on: push

stages: 
  - 
    displayName: "Build stage"
    jobs: 
      - 
        job: BuildJob
        pool: mypool
        steps: 
          - 
            displayName: "Use Python $(pythonVersion)"
            inputs: 
              addToPath: true
              architecture: x64
              versionSpec: $(pythonVersion)
            task: UsePythonVersion@0
          - 
            displayName: "Install requirements"
            script: |
                python3.7 -m venv antenv
                source antenv/bin/activate
                python3.7 -m pip install --upgrade pip
                pip install setup
                pip install -r requirements.txt
            workingDirectory: $(projectRoot)
          - 
            displayName: "Archive files"
            inputs: 
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              archiveType: zip
              includeRootFolder: false
              replaceExistingArchive: true
              rootFolderOrFile: $(projectRoot)
            task: ArchiveFiles@2
          - 
            artifact: drop
            displayName: "Upload package"
            upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    stage: Build
  - 
    condition: succeeded()
    dependsOn: Build
    displayName: "Deploy Web App"
    jobs: 
      - 
        deployment: DeploymentJob
        environment: $(environmentName)
        pool: mypool
        strategy: 
          runOnce: 
            deploy: 
              steps: 
                - 
                  displayName: "Use Python version"
                  inputs: 
                    versionSpec: $(pythonVersion)
                  task: UsePythonVersion@0
                - 
                  displayName: "Deploy Azure Web App : ay-flask-ml-service"
                  inputs: 
                    appName: $(webAppName)
                    azureSubscription: $(azureServiceConnectionId)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
                  task: AzureWebApp@1
    stage: Deploy
trigger: main
variables: 
  azureServiceConnectionId: 20858b90-cde6-4fe3-844f-741fda39cf99
  environmentName: ay-flask-ml-service
  pool: mypool
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: "3.7"
  vmImageName: ubuntu-latest
  webAppName: ay-flask-ml-service
